function GetEventListFunction()
{
	var i = 0;
	var eventlist = new Array();
	eventlist[i++] = new Array("10/07/2017", "Fall Crown Tournament", "");
	eventlist[i++] = new Array("10/14/2017", "Ansteorra Coronation", "");
	eventlist[i++] = new Array("10/21/2017", "", "");
	eventlist[i++] = new Array("10/28/2017", "", "");
	eventlist[i++] = new Array("11/04/2017", "", "");
	eventlist[i++] = new Array("11/11/2017", "Æthelmearc and East Kingdom War (Corn maze)", "http://aethelmearc.org/event/aethelmearc-and-east-kingdom-war-2017/");
	eventlist[i++] = new Array("11/18/2017", "", "");
	eventlist[i++] = new Array("11/25/2017", "", "");
	eventlist[i++] = new Array("12/02/2017", "Christmas Tourney 46 (Middle Kingdom)", "https://christmastourney.weebly.com/");
	eventlist[i++] = new Array("12/09/2017", "Fall Queen’s Rapier Championship", "http://aethelmearc.org/event/fall-queens-rapier-championship-2017/");
	eventlist[i++] = new Array("12/16/2017", "", "");
	eventlist[i++] = new Array("12/23/2017", "", "");
	eventlist[i++] = new Array("12/30/2017", "", "");
	eventlist[i++] = new Array("01/06/2018", "Æthelmearc Twelfth Night", "http://aethelmearc.org/event/twelfth-night-preferred-date-region-1-west-virginia/");
	eventlist[i++] = new Array("01/13/2018", "Debatable Lands 12th Night", "http://aethelmearc.org/event/debatable-lands-12th-night-2018/");
	eventlist[i++] = new Array("01/20/2018", "", "");
	eventlist[i++] = new Array("01/27/2018", "Regular event in the Cleftlands", "http://regular.cleftlands.org/");
	eventlist[i++] = new Array("02/03/2018", "Candlemas XXX", "https://shireofdragonsmark.org/event/candlemas_xxx");
	eventlist[i++] = new Array("02/10/2018", "", "");
	eventlist[i++] = new Array("02/17/2018", "AEdult Swim (Prince only)", "http://aethelmearc.org/event/aedult-swim/");
	eventlist[i++] = new Array("02/17/2018", "Midwinter Feast ~ Sydäntalvenjuhla (Princess only)", "http://midwinter2018.webs.com/");
	eventlist[i++] = new Array("02/24/2018", "St. Vals / Scots Welsh War Practice in Trimaris (Princess only)", "https://sites.google.com/trimaris.org/svsw2018/mainpages");
	eventlist[i++] = new Array("03/03/2018", "Tournament of the White Hart XXI", "http://aethelmearc.org/event/tournament-of-the-white-hart-xxi-le-livre-de-chasse/");
	eventlist[i++] = new Array("03/10/2018", "", "");
	eventlist[i++] = new Array("03/17/2018", "", "");
	eventlist[i++] = new Array("03/24/2018", "The Donnan Party", "http://aethelmearc.org/event/the-donnan-party-2018/");
	eventlist[i++] = new Array("03/31/2018", "", "");
	eventlist[i++] = new Array("04/07/2018", "", "");
	eventlist[i++] = new Array("04/14/2018", "The Festival of the Passing of the Ice Dragon", "http://aethelmearc.org/event/the-festival-of-the-passing-of-the-ice-dragon/");
	eventlist[i++] = new Array("04/21/2018", "AEthelmearc Spring Coronation", "http://aethelmearc.org/event/coronation-for-sven-and-siobhan/");
	eventlist[i++] = new Array("04/28/2018", "Blackstone Raid", "http://aethelmearc.org/event/blackstone-raid-xxvii/");
	eventlist[i++] = new Array("05/05/2018", "Midrealm Coronation", "http://middlemarches.org/coronation.html");
	eventlist[i++] = new Array("05/12/2018", "Spring Crown (Nanticoke, PA)", "http://aethelmearc.org/event/spring-crown-tournament-preferred-date-region-2-western-pa/");
	eventlist[i++] = new Array("05/19/2018", "Æthelmearc War Practice", "http://aethelmearc.org/event/aethelmearc-war-practice/");
	eventlist[i++] = new Array("05/26/2018", "", "");
	eventlist[i++] = new Array("06/02/2018", "Myrkfaelinn Summer War Practice", "http://aethelmearc.org/event/myrkfaelinn-summer-war-practice-2018/");
	eventlist[i++] = new Array("06/09/2018", "The Scarlet Guard Inn Archery Festival VI","http://aethelmearc.org/event/the-scarlet-guard-inn-archery-festival-vi/");
	eventlist[i++] = new Array("06/16/2018", "Spring Æthelmearc AEcademy and War College", "http://aethelmearc.org/event/spring-aethelmearc-academy-preferred-date-region-3-eastern-pa/");
	eventlist[i++] = new Array("06/23/2018", "Kingdom A&S Faire", "http://aethelmearc.org/event/kingdom-as-faire/");
	eventlist[i++] = new Array("06/30/2018", "East Kingdom 50 Year Celebration", "https://www.eastkingdom.org/EventDetails.php?eid=3161");
	eventlist[i++] = new Array("07/07/2018", "[Family obligation] and Pax Interruptus XXXXII", "http://aethelmearc.org/event/pax-interruptus-xxxxii/");
	eventlist[i++] = new Array("07/14/2018", "Bog Three Days", "http://aethelmearc.org/event/bog-three-day-2018/");
	eventlist[i++] = new Array("07/21/2018", "", "");
	eventlist[i++] = new Array("07/28/2018", "Pennsic", "http://www.pennsicwar.org");
	eventlist[i++] = new Array("08/04/2018", "Pennsic", "http://www.pennsicwar.org");
	eventlist[i++] = new Array("08/11/2018", "Pennsic", "http://www.pennsicwar.org");
	eventlist[i++] = new Array("08/18/2018", "", "");
	eventlist[i++] = new Array("08/25/2018", "", "");
	eventlist[i++] = new Array("09/01/2018", "", "");
	eventlist[i++] = new Array("09/08/2018", "", "");
	eventlist[i++] = new Array("09/15/2018", "Fall Coronation preferred date", "");
	eventlist[i++] = new Array("09/22/2018", "", "");
	eventlist[i++] = new Array("09/29/2018", "", "");

	return eventlist;
}
